
// ============================================
// DIRHAMI - Données OPCVM Maroc (CORRIGÉ)
// Plus d'OPCVM Actions, moins d'obligations
// ============================================

const opcvmData = [
    // ========== OPCVM ACTIONS (8 fonds) ==========
    {
        id: 'bmce-maroc-valeurs',
        nom: 'Maroc Valeurs',
        categorie: 'Actions',
        societeGestion: 'BMCE Capital Gestion',
        vl: 7586.32,
        actifNet: 594790544,
        fraisGestion: 2.00,
        fraisEntree: 3.00,
        fraisSortie: 0,
        performance1M: -4.59,
        performance3M: -2.34,
        performance6M: -6.36,
        performance1A: -1.41,
        performance3A: 61.06,
        performanceYTD: -3.39,
        benchmark: 'MASI',
        volatilite: 'Élevée',
        horizon: '> 3 ans',
        risque: 4,
        description: 'Gestion active et sélective de valeurs mobilières marocaines'
    },
    {
        id: 'cdg-actions',
        nom: 'CDG Actions',
        categorie: 'Actions',
        societeGestion: 'CDG Capital',
        vl: 4521.80,
        actifNet: 320000000,
        fraisGestion: 1.80,
        fraisEntree: 2.50,
        fraisSortie: 0,
        performance1M: -3.20,
        performance3M: -1.50,
        performance6M: -4.80,
        performance1A: 2.10,
        performance3A: 45.30,
        performanceYTD: -2.10,
        benchmark: 'MASI',
        volatilite: 'Élevée',
        horizon: '> 3 ans',
        risque: 4,
        description: 'Investissement en actions cotées à la Bourse de Casablanca'
    },
    {
        id: 'attijari-actions',
        nom: 'Wafa Actions',
        categorie: 'Actions',
        societeGestion: 'Wafa Gestion',
        vl: 3890.50,
        actifNet: 280000000,
        fraisGestion: 2.10,
        fraisEntree: 3.00,
        fraisSortie: 0,
        performance1M: -3.80,
        performance3M: -2.10,
        performance6M: -5.50,
        performance1A: 0.50,
        performance3A: 52.80,
        performanceYTD: -2.80,
        benchmark: 'MASI',
        volatilite: 'Élevée',
        horizon: '> 3 ans',
        risque: 4,
        description: 'Sélection active des meilleures opportunités du marché actions'
    },
    {
        id: 'sg-actions',
        nom: 'SG Actions Maroc',
        categorie: 'Actions',
        societeGestion: 'SG Gestion',
        vl: 3245.60,
        actifNet: 150000000,
        fraisGestion: 1.90,
        fraisEntree: 2.50,
        fraisSortie: 0,
        performance1M: -2.90,
        performance3M: -0.80,
        performance6M: -3.90,
        performance1A: 3.20,
        performance3A: 48.50,
        performanceYTD: -1.50,
        benchmark: 'MASI',
        volatilite: 'Élevée',
        horizon: '> 3 ans',
        risque: 4,
        description: 'Gestion active orientée valeur'
    },
    {
        id: 'bp-actions',
        nom: 'BP Actions',
        categorie: 'Actions',
        societeGestion: 'Banque Populaire Gestion',
        vl: 4120.30,
        actifNet: 210000000,
        fraisGestion: 1.85,
        fraisEntree: 2.50,
        fraisSortie: 0,
        performance1M: -3.10,
        performance3M: -1.20,
        performance6M: -4.50,
        performance1A: 1.80,
        performance3A: 50.20,
        performanceYTD: -2.20,
        benchmark: 'MASI',
        volatilite: 'Élevée',
        horizon: '> 3 ans',
        risque: 4,
        description: 'Investissement diversifié en actions marocaines'
    },
    {
        id: 'boa-actions',
        nom: 'BOA Actions',
        categorie: 'Actions',
        societeGestion: 'BOA Gestion',
        vl: 3650.80,
        actifNet: 180000000,
        fraisGestion: 1.95,
        fraisEntree: 2.50,
        fraisSortie: 0,
        performance1M: -3.50,
        performance3M: -1.80,
        performance6M: -5.20,
        performance1A: 0.80,
        performance3A: 47.60,
        performanceYTD: -2.60,
        benchmark: 'MASI',
        volatilite: 'Élevée',
        horizon: '> 3 ans',
        risque: 4,
        description: 'Stratégie de croissance sur le marché actions marocain'
    },
    {
        id: 'cfg-actions',
        nom: 'CFG Actions',
        categorie: 'Actions',
        societeGestion: 'CFG Gestion',
        vl: 2980.40,
        actifNet: 120000000,
        fraisGestion: 1.75,
        fraisEntree: 2.00,
        fraisSortie: 0,
        performance1M: -2.60,
        performance3M: -0.50,
        performance6M: -3.40,
        performance1A: 4.10,
        performance3A: 42.80,
        performanceYTD: -1.20,
        benchmark: 'MASI',
        volatilite: 'Élevée',
        horizon: '> 3 ans',
        risque: 4,
        description: 'Approche value investing sur les actions marocaines'
    },
    {
        id: 'cih-actions',
        nom: 'CIH Actions',
        categorie: 'Actions',
        societeGestion: 'CIH Gestion',
        vl: 3420.90,
        actifNet: 160000000,
        fraisGestion: 1.90,
        fraisEntree: 2.50,
        fraisSortie: 0,
        performance1M: -3.00,
        performance3M: -1.00,
        performance6M: -4.10,
        performance1A: 2.50,
        performance3A: 49.30,
        performanceYTD: -1.90,
        benchmark: 'MASI',
        volatilite: 'Élevée',
        horizon: '> 3 ans',
        risque: 4,
        description: 'Gestion active avec focus sur les grandes capitalisations'
    },

    // ========== OPCVM OBLIGATIONS (3 fonds) ==========
    {
        id: 'bmce-obligations',
        nom: 'Maroc Obligations',
        categorie: 'Obligations',
        societeGestion: 'BMCE Capital Gestion',
        vl: 10542.30,
        actifNet: 420000000,
        fraisGestion: 1.20,
        fraisEntree: 1.00,
        fraisSortie: 0,
        performance1M: 0.30,
        performance3M: 0.90,
        performance6M: 1.80,
        performance1A: 4.20,
        performance3A: 15.60,
        performanceYTD: 1.20,
        benchmark: 'Index Obligations',
        volatilite: 'Faible',
        horizon: '2-5 ans',
        risque: 2,
        description: 'Investissement en obligations souveraines et corporate'
    },
    {
        id: 'cdg-obligations',
        nom: 'CDG Obligations',
        categorie: 'Obligations',
        societeGestion: 'CDG Capital',
        vl: 9850.20,
        actifNet: 380000000,
        fraisGestion: 1.00,
        fraisEntree: 1.00,
        fraisSortie: 0,
        performance1M: 0.25,
        performance3M: 0.80,
        performance6M: 1.60,
        performance1A: 3.80,
        performance3A: 14.20,
        performanceYTD: 1.00,
        benchmark: 'Index Obligations',
        volatilite: 'Faible',
        horizon: '2-5 ans',
        risque: 2,
        description: 'Placement sécurisé en obligations du Trésor'
    },
    {
        id: 'attijari-obligations',
        nom: 'Wafa Obligations',
        categorie: 'Obligations',
        societeGestion: 'Wafa Gestion',
        vl: 11230.40,
        actifNet: 290000000,
        fraisGestion: 1.30,
        fraisEntree: 1.50,
        fraisSortie: 0,
        performance1M: 0.35,
        performance3M: 1.00,
        performance6M: 2.00,
        performance1A: 4.50,
        performance3A: 16.80,
        performanceYTD: 1.30,
        benchmark: 'Index Obligations',
        volatilite: 'Faible',
        horizon: '2-5 ans',
        risque: 2,
        description: 'Diversification en obligations souveraines et privées'
    },

    // ========== OPCVM DIVERSIFIÉS (3 fonds) ==========
    {
        id: 'bmce-equilibre',
        nom: 'Maroc Equilibre',
        categorie: 'Diversifié',
        societeGestion: 'BMCE Capital Gestion',
        vl: 8920.60,
        actifNet: 350000000,
        fraisGestion: 1.50,
        fraisEntree: 2.00,
        fraisSortie: 0,
        performance1M: -1.20,
        performance3M: -0.30,
        performance6M: -1.50,
        performance1A: 2.80,
        performance3A: 28.40,
        performanceYTD: -0.80,
        benchmark: 'Mixte',
        volatilite: 'Moyenne',
        horizon: '3-5 ans',
        risque: 3,
        description: 'Répartition équilibrée entre actions et obligations'
    },
    {
        id: 'cdg-diversifie',
        nom: 'CDG Diversifié',
        categorie: 'Diversifié',
        societeGestion: 'CDG Capital',
        vl: 7650.30,
        actifNet: 280000000,
        fraisGestion: 1.40,
        fraisEntree: 2.00,
        fraisSortie: 0,
        performance1M: -0.90,
        performance3M: 0.10,
        performance6M: -0.80,
        performance1A: 3.50,
        performance3A: 25.60,
        performanceYTD: -0.50,
        benchmark: 'Mixte',
        volatilite: 'Moyenne',
        horizon: '3-5 ans',
        risque: 3,
        description: 'Stratégie de diversification patrimoniale'
    },
    {
        id: 'attijari-equilibre',
        nom: 'Wafa Equilibre',
        categorie: 'Diversifié',
        societeGestion: 'Wafa Gestion',
        vl: 8340.90,
        actifNet: 220000000,
        fraisGestion: 1.60,
        fraisEntree: 2.50,
        fraisSortie: 0,
        performance1M: -1.10,
        performance3M: -0.20,
        performance6M: -1.30,
        performance1A: 2.60,
        performance3A: 27.20,
        performanceYTD: -0.70,
        benchmark: 'Mixte',
        volatilite: 'Moyenne',
        horizon: '3-5 ans',
        risque: 3,
        description: 'Allocation dynamique actions/obligations'
    },

    // ========== OPCVM MONÉTAIRES (3 fonds) ==========
    {
        id: 'bmce-monnaie',
        nom: 'Maroc Monnaie',
        categorie: 'Monétaire',
        societeGestion: 'BMCE Capital Gestion',
        vl: 10250.80,
        actifNet: 500000000,
        fraisGestion: 0.50,
        fraisEntree: 0,
        fraisSortie: 0,
        performance1M: 0.15,
        performance3M: 0.45,
        performance6M: 0.90,
        performance1A: 2.10,
        performance3A: 7.80,
        performanceYTD: 0.60,
        benchmark: 'TMM',
        volatilite: 'Très faible',
        horizon: '< 1 an',
        risque: 1,
        description: 'Liquidité et sécurité du capital'
    },
    {
        id: 'cdg-monnaie',
        nom: 'CDG Monnaie',
        categorie: 'Monétaire',
        societeGestion: 'CDG Capital',
        vl: 10180.40,
        actifNet: 450000000,
        fraisGestion: 0.40,
        fraisEntree: 0,
        fraisSortie: 0,
        performance1M: 0.12,
        performance3M: 0.40,
        performance6M: 0.85,
        performance1A: 1.90,
        performance3A: 7.20,
        performanceYTD: 0.50,
        benchmark: 'TMM',
        volatilite: 'Très faible',
        horizon: '< 1 an',
        risque: 1,
        description: 'Placement de trésorerie à court terme'
    },
    {
        id: 'attijari-monnaie',
        nom: 'Wafa Monnaie',
        categorie: 'Monétaire',
        societeGestion: 'Wafa Gestion',
        vl: 10320.10,
        actifNet: 380000000,
        fraisGestion: 0.55,
        fraisEntree: 0,
        fraisSortie: 0,
        performance1M: 0.18,
        performance3M: 0.50,
        performance6M: 1.00,
        performance1A: 2.20,
        performance3A: 8.10,
        performanceYTD: 0.65,
        benchmark: 'TMM',
        volatilite: 'Très faible',
        horizon: '< 1 an',
        risque: 1,
        description: 'Sécurité et disponibilité immédiate'
    },

    // ========== OPCVM ISLAMIQUES (2 fonds) ==========
    {
        id: 'bmce-islamique',
        nom: 'Maroc Islamique',
        categorie: 'Islamique',
        societeGestion: 'BMCE Capital Gestion',
        vl: 6780.50,
        actifNet: 180000000,
        fraisGestion: 1.80,
        fraisEntree: 2.50,
        fraisSortie: 0,
        performance1M: -2.80,
        performance3M: -1.50,
        performance6M: -4.20,
        performance1A: 1.20,
        performance3A: 38.50,
        performanceYTD: -2.00,
        benchmark: 'MASI',
        volatilite: 'Moyenne',
        horizon: '> 3 ans',
        risque: 3,
        description: 'Investissement conforme à la Charia'
    },
    {
        id: 'cdg-islamique',
        nom: 'CDG Islamique',
        categorie: 'Islamique',
        societeGestion: 'CDG Capital',
        vl: 7120.30,
        actifNet: 150000000,
        fraisGestion: 1.60,
        fraisEntree: 2.00,
        fraisSortie: 0,
        performance1M: -2.50,
        performance3M: -1.20,
        performance6M: -3.80,
        performance1A: 1.80,
        performance3A: 35.20,
        performanceYTD: -1.80,
        benchmark: 'MASI',
        volatilite: 'Moyenne',
        horizon: '> 3 ans',
        risque: 3,
        description: 'Finance participative et investissement éthique'
    }
];

const categoriesOPCVM = ['Toutes', 'Actions', 'Obligations', 'Diversifié', 'Monétaire', 'Islamique'];
const societesGestion = [...new Set(opcvmData.map(o => o.societeGestion))];

function filtrerOPCVM(filters) {
    return opcvmData.filter(opcvm => {
        if (filters.categorie && filters.categorie !== 'Toutes' && opcvm.categorie !== filters.categorie) return false;
        if (filters.societe && filters.societe !== 'Toutes' && opcvm.societeGestion !== filters.societe) return false;
        if (filters.risqueMax && opcvm.risque > filters.risqueMax) return false;
        if (filters.fraisMax && opcvm.fraisGestion > filters.fraisMax) return false;
        return true;
    });
}

function calculerRentabiliteNette(opcvm, montant, dureeAnnees) {
    const tauxAnnuel = opcvm.performance1A / 100;
    const fraisTotal = opcvm.fraisGestion / 100 + (opcvm.fraisEntree / 100);
    const tauxNet = tauxAnnuel - fraisTotal;
    const valeurFinale = montant * Math.pow(1 + tauxNet, dureeAnnees);
    const gain = valeurFinale - montant;
    const fraisPayes = montant * fraisTotal * dureeAnnees;

    return {
        montantInitial: montant,
        valeurFinale: Math.round(valeurFinale),
        gain: Math.round(gain),
        fraisPayes: Math.round(fraisPayes),
        tauxBrut: opcvm.performance1A,
        tauxNet: (tauxNet * 100).toFixed(2)
    };
}

function comparerOPCVM(opcvm1, opcvm2, montant, duree) {
    const r1 = calculerRentabiliteNette(opcvm1, montant, duree);
    const r2 = calculerRentabiliteNette(opcvm2, montant, duree);

    return {
        opcvm1: { nom: opcvm1.nom, ...r1 },
        opcvm2: { nom: opcvm2.nom, ...r2 },
        difference: r1.gain - r2.gain,
        meilleur: r1.gain > r2.gain ? opcvm1.nom : opcvm2.nom
    };
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { opcvmData, categoriesOPCVM, societesGestion, filtrerOPCVM, calculerRentabiliteNette, comparerOPCVM };
}
