services:
  - type: web
    name: dirhami-backend
    env: node
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && node server.js"

  - type: web
    name: dirhami-frontend
    env: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm start"
