server {
    listen 80;
    server_name dirhami.ma www.dirhami.ma;

    location / {
        root /var/www/dirhami.ma/frontend;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        include proxy_params;
        proxy_pass http://unix:/var/www/dirhami.ma/backend/dirhami.sock;
    }

    location /static {
        alias /var/www/dirhami.ma/frontend;
    }
}
