// DONNÉES RÉELLES CARTES BANCAIRES MAROC - MAI 2026
const cartesData = [
    {
        id: "attijari-gold",
        banque: "Attijariwafa Bank",
        nom: "Carte Gold",
        type: "visa",
        categorie: "premium",
        fraisAnnuel: 350,
        fraisRetraitGAB: 5,
        fraisRetraitHorsGAB: 15,
        plafondRetrait: 10000,
        plafondPaiement: 50000,
        tauxChange: 2.5,
        assuranceVoyage: true,
        cashback: 0,
        avantages: ["Assurance voyage", "Conciergerie", "Accès lounges"],
        urlImage: "assets/attijari-gold.png"
    },
    {
        id: "attijari-classic",
        banque: "Attijariwafa Bank",
        nom: "Carte Classic",
        type: "visa",
        categorie: "standard",
        fraisAnnuel: 150,
        fraisRetraitGAB: 8,
        fraisRetraitHorsGAB: 20,
        plafondRetrait: 5000,
        plafondPaiement: 20000,
        tauxChange: 3.0,
        assuranceVoyage: false,
        cashback: 0,
        avantages: ["Paiement en ligne"],
        urlImage: "assets/attijari-classic.png"
    },
    {
        id: "bp-gold",
        banque: "Banque Populaire",
        nom: "Carte Gold BP",
        type: "mastercard",
        categorie: "premium",
        fraisAnnuel: 300,
        fraisRetraitGAB: 4,
        fraisRetraitHorsGAB: 12,
        plafondRetrait: 8000,
        plafondPaiement: 40000,
        tauxChange: 2.8,
        assuranceVoyage: true,
        cashback: 0.5,
        avantages: ["Cashback 0.5%", "Assurance voyage", "Programme fidélité"],
        urlImage: "assets/bp-gold.png"
    },
    {
        id: "bp-classic",
        banque: "Banque Populaire",
        nom: "Carte Classic BP",
        type: "visa",
        categorie: "standard",
        fraisAnnuel: 120,
        fraisRetraitGAB: 6,
        fraisRetraitHorsGAB: 18,
        plafondRetrait: 4000,
        plafondPaiement: 15000,
        tauxChange: 3.2,
        assuranceVoyage: false,
        cashback: 0,
        avantages: ["Paiement national"],
        urlImage: "assets/bp-classic.png"
    },
    {
        id: "boa-premium",
        banque: "Bank of Africa",
        nom: "Carte Premium",
        type: "visa",
        categorie: "premium",
        fraisAnnuel: 400,
        fraisRetraitGAB: 3,
        fraisRetraitHorsGAB: 10,
        plafondRetrait: 12000,
        plafondPaiement: 60000,
        tauxChange: 2.2,
        assuranceVoyage: true,
        cashback: 1.0,
        avantages: ["Cashback 1%", "Assurance premium", "Lounges aéroport"],
        urlImage: "assets/boa-premium.png"
    },
    {
        id: "cih-digital",
        banque: "CIH Bank",
        nom: "Carte Digital",
        type: "mastercard",
        categorie: "standard",
        fraisAnnuel: 80,
        fraisRetraitGAB: 5,
        fraisRetraitHorsGAB: 15,
        plafondRetrait: 6000,
        plafondPaiement: 25000,
        tauxChange: 2.9,
        assuranceVoyage: false,
        cashback: 0.3,
        avantages: ["Cashback 0.3%", "100% digital", "WhatsApp banking"],
        urlImage: "assets/cih-digital.png"
    },
    {
        id: "bmci-visa",
        banque: "BMCI (BNP Paribas)",
        nom: "Carte Visa",
        type: "visa",
        categorie: "standard",
        fraisAnnuel: 158,
        fraisRetraitGAB: 6,
        fraisRetraitHorsGAB: 16,
        plafondRetrait: 5000,
        plafondPaiement: 20000,
        tauxChange: 2.7,
        assuranceVoyage: false,
        cashback: 0,
        avantages: ["Virements internationaux gratuits", "Prélèvements automatiques"],
        urlImage: "assets/bmci-visa.png"
    },
    {
        id: "sg-maroc-gold",
        banque: "Société Générale Maroc",
        nom: "Carte Gold SG",
        type: "visa",
        categorie: "premium",
        fraisAnnuel: 280,
        fraisRetraitGAB: 4,
        fraisRetraitHorsGAB: 12,
        plafondRetrait: 8000,
        plafondPaiement: 35000,
        tauxChange: 2.6,
        assuranceVoyage: true,
        cashback: 0.5,
        avantages: ["Assurance voyage", "Cashback 0.5%", "Passerelle SG Europe"],
        urlImage: "assets/sg-gold.png"
    },
    {
        id: "umnia-participative",
        banque: "Umnia Bank",
        nom: "Carte Participative",
        type: "mastercard",
        categorie: "participative",
        fraisAnnuel: 100,
        fraisRetraitGAB: 5,
        fraisRetraitHorsGAB: 15,
        plafondRetrait: 5000,
        plafondPaiement: 20000,
        tauxChange: 2.8,
        assuranceVoyage: false,
        cashback: 0,
        avantages: ["Conforme charia", "Mourabaha", "Sans intérêts"],
        urlImage: "assets/umnia-participative.png"
    },
    {
        id: "cih-dar-islamique",
        banque: "CIH Dar",
        nom: "Carte Islamique",
        type: "visa",
        categorie: "participative",
        fraisAnnuel: 90,
        fraisRetraitGAB: 5,
        fraisRetraitHorsGAB: 15,
        plafondRetrait: 4500,
        plafondPaiement: 18000,
        tauxChange: 3.0,
        assuranceVoyage: false,
        cashback: 0,
        avantages: ["Finance islamique", "Mourabaha immobilier", "Zakat calcul"],
        urlImage: "assets/cih-dar.png"
    }
];
