// DONNÉES OPCVM MAROC - MAI 2026 (Sources: AMMC, tamra.ma, wafir.ma)
const opcvmData = [
    {
        id: "maroc-valeurs",
        nom: "MAROC VALEURS",
        societe: "Wafa Gestion",
        categorie: "Actions Maroc",
        type: "actions",
        rendement1An: 12.5,
        rendement3Ans: 8.2,
        rendement5Ans: 6.8,
        fraisGestion: 2.00,
        fraisEntree: 2.00,
        fraisSortie: 0,
        volatilite: "Élevée",
        capitalMinimum: 1000,
        description: "Fonds investi à 90% en actions des grandes capitalisations marocaines cotées à la Bourse de Casablanca.",
        composition: ["Attijariwafa Bank 15%", "Maroc Telecom 12%", "LafargeHolcim 10%", "Bmce Bank 8%", "Other 55%"],
        benchmark: "MASI",
        urlAMMC: "https://www.ammc.ma"
    },
    {
        id: "wafa-tresorerie",
        nom: "WAFA TRÉSORERIE",
        societe: "Wafa Gestion",
        categorie: "Monétaire",
        type: "monetaire",
        rendement1An: 3.2,
        rendement3Ans: 3.0,
        rendement5Ans: 2.8,
        fraisGestion: 0.50,
        fraisEntree: 0,
        fraisSortie: 0,
        volatilite: "Faible",
        capitalMinimum: 500,
        description: "Fonds monétaire sans risque, idéal pour la trésorerie de court terme.",
        composition: ["Bons de trésor 80%", "Dépôts à terme 20%"],
        benchmark: "Taux directeur BAM",
        urlAMMC: "https://www.ammc.ma"
    },
    {
        id: "bmce-growth",
        nom: "BMCE GROWTH",
        societe: "BMCE Capital Gestion",
        categorie: "Actions Maroc",
        type: "actions",
        rendement1An: 10.8,
        rendement3Ans: 7.5,
        rendement5Ans: 5.9,
        fraisGestion: 1.80,
        fraisEntree: 1.50,
        fraisSortie: 0,
        volatilite: "Élevée",
        capitalMinimum: 1000,
        description: "Fonds orienté vers la croissance des PME marocaines cotées.",
        composition: ["Secteur bancaire 25%", "Immobilier 20%", "Industrie 30%", "Services 25%"],
        benchmark: "MASI",
        urlAMMC: "https://www.ammc.ma"
    },
    {
        id: "attijari-obligations",
        nom: "ATTIJARI OBLIGATIONS",
        societe: "Attijari Intermediation",
        categorie: "Obligations",
        type: "obligations",
        rendement1An: 5.5,
        rendement3Ans: 5.2,
        rendement5Ans: 4.8,
        fraisGestion: 1.00,
        fraisEntree: 1.00,
        fraisSortie: 0,
        volatilite: "Moyenne",
        capitalMinimum: 5000,
        description: "Fonds obligataire investi dans les emprunts d'État et obligations corporate marocaines.",
        composition: ["Emprunts d'État 60%", "Obligations bancaires 25%", "Corporate 15%"],
        benchmark: "Index obligations Maroc",
        urlAMMC: "https://www.ammc.ma"
    },
    {
        id: "bp-diversifie",
        nom: "BCP DIVERSIFIÉ",
        societe: "BCP Capital",
        categorie: "Diversifié",
        type: "diversifie",
        rendement1An: 7.2,
        rendement3Ans: 6.0,
        rendement5Ans: 5.2,
        fraisGestion: 1.50,
        fraisEntree: 1.50,
        fraisSortie: 0.50,
        volatilite: "Moyenne",
        capitalMinimum: 2000,
        description: "Fonds diversifié actions/obligations pour un équilibre rendement/risque.",
        composition: ["Actions 50%", "Obligations 40%", "Liquidité 10%"],
        benchmark: "50% MASI / 50% Obligations",
        urlAMMC: "https://www.ammc.ma"
    },
    {
        id: "cih-islamique",
        nom: "CIH ISLAMIQUE ACTIONS",
        societe: "CIH Gestion",
        categorie: "Actions Maroc",
        type: "participative",
        rendement1An: 9.5,
        rendement3Ans: 6.8,
        rendement5Ans: 5.5,
        fraisGestion: 1.75,
        fraisEntree: 1.50,
        fraisSortie: 0,
        volatilite: "Élevée",
        capitalMinimum: 1000,
        description: "Fonds actions conforme aux principes de la finance islamique (exclusion secteurs haram).",
        composition: ["Secteur halal 100%"],
        benchmark: "MASI Islamique",
        urlAMMC: "https://www.ammc.ma"
    },
    {
        id: "boa-patrimoine",
        nom: "BOA PATRIMOINE",
        societe: "Bank of Africa Gestion",
        categorie: "Diversifié",
        type: "diversifie",
        rendement1An: 6.8,
        rendement3Ans: 5.5,
        rendement5Ans: 4.9,
        fraisGestion: 1.60,
        fraisEntree: 1.00,
        fraisSortie: 0,
        volatilite: "Moyenne",
        capitalMinimum: 5000,
        description: "Fonds patrimonial pour une clientèle exigeante, mix actions internationales et marocaines.",
        composition: ["Actions Maroc 40%", "Actions internationales 30%", "Obligations 25%", "Liquidité 5%"],
        benchmark: "Composite international",
        urlAMMC: "https://www.ammc.ma"
    },
    {
        id: "sg-maroc-equilibre",
        nom: "SG MAROC ÉQUILIBRE",
        societe: "SG Gestion Maroc",
        categorie: "Diversifié",
        type: "diversifie",
        rendement1An: 5.9,
        rendement3Ans: 5.1,
        rendement5Ans: 4.5,
        fraisGestion: 1.40,
        fraisEntree: 1.00,
        fraisSortie: 0,
        volatilite: "Moyenne",
        capitalMinimum: 1000,
        description: "Fonds équilibré pour profils prudents souhaitant un rendement régulier.",
        composition: ["Actions 35%", "Obligations 55%", "Liquidité 10%"],
        benchmark: "Composite 35/65",
        urlAMMC: "https://www.ammc.ma"
    },
    {
        id: "cdm-expansion",
        nom: "CDM EXPANSION",
        societe: "CDM Gestion",
        categorie: "Actions Maroc",
        type: "actions",
        rendement1An: 8.30,
        rendement3Ans: 6.5,
        rendement5Ans: 5.8,
        fraisGestion: 2.00,
        fraisEntree: 3.00,
        fraisSortie: 1.50,
        volatilite: "Élevée",
        capitalMinimum: 1000,
        description: "Objectif de croissance du capital à long terme via l'exposition aux actions marocaines.",
        composition: ["Actions MASI 100%"],
        benchmark: "MASI",
        urlAMMC: "https://www.ammc.ma"
    }
];
